### ISSUE TITLE
LICENSE and inclusion in Vim runtime?

### ISSUE THREAD

**Issue by benknoble** [mikelue/vim-maven-plugin#13]
👋 Hello vim-maven-plugin contributors!

I've been [approached about including a modified version of the compiler plugin in Vim](https://github.com/benknoble/Dotfiles/commit/570b1006fd794b0b9f5434b4fed4c2d785fcb05c#commitcomment-148504150), which is exciting! However, in order to do that ethically I need to know what license this code is provided under (otherwise all we can do with it is whatever is considered "fair use," and what I have in mind is more of a "derivative work").

To license the entire project, I need sign-off from everyone because there's no pre-existing licensing statement that I can point to which contributors might have implicitly agreed to.

Pick any license you want! I recommend some simple options, though:
- [MIT License](https://opensource.org/license/mit)
- [BSD 3-Clause License](https://opensource.org/license/bsd-3-clause)
- [Vim License](https://github.com/vim/vim/blob/master/LICENSE)

One simple way to go about this would be to have each of you respond with what licenses you find acceptable, and take any that are common to all 6 contributors.

cc: @mikelue @iamFIREcracker @sideshowcoder @richox @kmARC @mahdix 

---

If this is too much, being granted a license by the contributors to compiler/maven.vim would be sufficient for the work I have in mind. That's just @mikelue and @iamFIREcracker

**Comment by mikelue** [comment]
I've added LICENSE by [904c38d6e2643cab70c18c11da7e1b968b9e87ac](https://github.com/mikelue/vim-maven-plugin/commit/904c38d6e2643cab70c18c11da7e1b968b9e87ac)

Thanks a lot.

**Comment by sideshowcoder** [comment]
Sorry late to this as I haven't followed my github notifications, but am good with the Vim License added. Thank you for your work!

**Comment by iamFIREcracker** [comment]
Hey, sorry for the late reply.  Anyways, for what is worth, I am fine with the Vim License being used for this (my changes included).  Thanks for pushing this through!

**Comment by benknoble** [comment]
Thanks both!
