### ISSUE TITLE
File name problem in Windows

### ISSUE THREAD

**Issue by NLKNguyen** [mikelue/vim-maven-plugin#3]
Hi, thanks for the plugin. However, on Windows, the file name in Quickfix window has the extra prefix `\` that prevent navigating to the correct file.

In this example, if I [Enter] on the file, it will navigate to an incorrect path: `C:\C:\Users\NLKNg\Desktop\helloSpring\src\main\java\hello\HelloController.java`

![capture](https://cloud.githubusercontent.com/assets/4667129/12012747/1119b9c0-acb8-11e5-8b8d-fecd1652c6a2.PNG)

**Comment by mikelue** [comment]
I have fixed the bug while 'shellslash' is 0 in windows system.
Appreciate your feedback. Please get the last version and try again.

**Comment by NLKNguyen** [comment]
Thanks! It works now :+1:
