### ISSUE TITLE
Error when opening an empty pom.xml

### ISSUE THREAD

**Issue by NLKNguyen** [mikelue/vim-maven-plugin#4]
Even though this doesn't cause me trouble or anything, I think maybe you'd like to know.

![capture](https://cloud.githubusercontent.com/assets/4667129/12108835/a7371ece-b330-11e5-9c4c-6bb04ee04cce.PNG)

**Comment by NLKNguyen** [comment]
Actually, even if there is content in pom.xml, this error still shows.

**Comment by mikelue** [comment]
This problem seems disappeared and I don't know why.
